#kind: pipeline
#name: default

#steps:
#- name: build-java-app
 # image: houcemserver/mydevops:latest
  #pull: if-not-exists
  #settings:
  #  goals: 
   # - clean 
    #- install 
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
